name: Deploy to Trigger.dev (prod)

on:
  push:
    branches:
      - master
    paths:
      - "src/trigger/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
         bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          bunx trigger.dev@beta deploy